### ISSUE TITLE
Fix MLP

### ISSUE THREAD

**Issue by HAndradi** [HAndradi/NN_Assignment_6#1]
Since there are way more positive examples than negative examples, the MLP model just learns to classify all inputs as positive. Therefore either the MLP model needs to be changed and tuned to get better results.

**Comment by carlowiesse** [comment]
[FIXED]
- learning rate set to 1e-06, optimizer set to Adam
- new architecture -> 1 hidden layer (1021,relu) + 1 output layer (1,sigmoid)
- output (for me last time I ran it) -> precision (0.98), recall (0.98)
